### ISSUE TITLE
Feature request: shift word end when shifting segment OR shift segment when deleting words

### ISSUE THREAD

**Issue by PaulLerner** [gong-io/gecko#69]
Hi again,

I think it's currently quite tricky to correct ASR or forced-alignment timing errors (see also #68).

I propose two alternative solutions :
-  shift word end when shifting segment : currently, only the beginning of the word (i.e. `term.start`) is shifted when one shifts a segment (i.e. drags a region starting point from left to right). I assume the behaviour is symmetrical if shifting a region from right to left. I propose that you shift the end of the word (i.e. `term.end`) to keep the same word duration as before the shifting (idem if you shift the segment from right to left).
- shift segment when deleting words. I mean setting `speaker.start` at `terms[0].start` and `speaker.end` at  `terms[-1].end`. Of course this could be a post-processing step if only the words were shifted when shifting a segment (my first proposal).

I can take care of it if you agree on one solution and tell me where that happens :)

Bests,

**Comment by GolanLevy** [comment]
Hi Paul, 

By speaker.end/start do you mean region.staret/end?

Anyway, we do not care about words alignment in text because we use post-processing automatic tools for that.
In the future we want to have a service that can be called and auto align the words on user's request, so the user can do it while he is working.

Are you sure you want to align each and every word?
Maybe I can direct you to some auto-alignment tools?

If you prefer to have it the way you suggested,
I recommend that you will provide a different format, e.g. "Aligned JSON", that will do the manipulations on save.

**Comment by PaulLerner** [comment]
Hi Golan,

Thank you for your answer, yes I mean `region.start/end` (sorry about that, it's hard to keep up between wavesurfer, gecko and pyannote).

I'm precisely trying to correct auto-alignment errors (this is what I mean by _forced-alignment_ timing errors). 
Even though we would like a segmentation as precise as possible (i.e. per word), we figured out another way to do it so I'm closing this for now.

Happy holidays

**Comment by GolanLevy** [comment]
For precision, you can always transform each word to a separate segment.
Would you mind to share how did you solve it?
